#!/usr/bin/env bash

killall -q polybar

if [[ -e "/sys/class/backlight/intel_backlight" ]]; then
    bar='mybar'
else
    bar='legion-discrete-gpu'
fi

while pgrep -u $UID -x polybar > /dev/null; do sleep 0.1; done

for monitor in $(polybar --list-monitors | cut -d: -f1); do
    MONITOR=$monitor polybar "$bar" &
done
